# ExplainIQ Contracts & Shared Specifications

EXPLAINIQ_ENGINE_VERSION = "1.0.0"
DEFAULT_TRANSPARENCY_RATING = "Excellent"
DEFAULT_EXPLAINABILITY_SCORE = 98.50
AUDIT_COMPLETENESS_RATIO = 100.00
DECISION_CONSISTENCY_RATIO = 95.00
